# Applying a Regresion to the overall scores of the lexical metrics and embeddings

In [1]:
import os
import pandas as pd
import numpy as np
from scipy.stats import zscore
from sklearn.linear_model import LinearRegression

lexical_path = "/Users/franz/Downloads/Text_Mining_Group_Project-main/Franz (lexical) - csvs with predictions/train/"
embeddings_path = "/Users/franz/Downloads/Text_Mining_Group_Project-main/Philipp (WM's distance) - csvs with predictions/train/"

In [2]:
lexical_train = os.listdir(lexical_path)
embeddings_train = os.listdir(embeddings_path)

In [3]:
print(lexical_train)

['zh_en_predictions.csv', 'en_zh_predictions.csv', 'de_en_predictions.csv', 'cs_en_predictions.csv', 'ru_en_predictions.csv', 'en_fi_predictions.csv']

In [4]:
print(embeddings_train)

['train_all_with_predictions_de_en.csv', 'train_all_with_predictions_ru_en.csv', 'train_all_with_predictions_en_fi.csv', 'train_all_with_predictions_en_zh.csv', 'train_all_with_predictions_cs_en.csv', 'train_all_with_predictions_zh_en.csv']

## RU - EN

In [5]:
kendalls = []
pearsons = []
p_e = []
p_l = []
k_e = []
k_l = []

In [6]:
l = pd.read_csv(lexical_path + 'ru_en_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_ru_en.csv')

In [7]:
l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
ru_en = e
ru_en["prediction_l"] = l["prediction_l"]

In [8]:
p = ru_en.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = ru_en.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.356313      0.365853
prediction_e -0.356313      1.000000     -0.910084
prediction_l  0.365853     -0.910084      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.241806      0.251615
prediction_e -0.241806      1.000000     -0.737054
prediction_l  0.251615     -0.737054      1.000000

In [9]:
for element in ["prediction_e", "prediction_l"]:
    ru_en[element] = zscore(ru_en[element])
    
ru_en__train = ru_en.iloc[:int(ru_en.shape[0]*0.7),:]
ru_en__test = ru_en.iloc[int(ru_en.shape[0]*0.7):,:]

X = ru_en__train.iloc[:,1:]
Y = ru_en__train.iloc[:,0]
X_test = ru_en__test.iloc[:,1:]
Y_test = ru_en__test.iloc[:,0] 
X_full = ru_en.iloc[:,1:]
Y_full = ru_en.iloc[:,0] 

model_ru_en = LinearRegression()
model_ru_en.fit(X,Y)

final_model_ru_en = LinearRegression()
final_model_ru_en.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_ru_en.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

                    z-score  regression_values
z-score            1.000000           0.371456
regression_values  0.371456           1.000000

                    z-score  regression_values
z-score            1.000000           0.258672
regression_values  0.258672           1.000000

## DE - EN

In [10]:
l = pd.read_csv(lexical_path + 'de_en_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_de_en.csv')

l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
de_en = e
de_en["prediction_l"] = l["prediction_l"]

p = de_en.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = de_en.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

for element in ["prediction_e", "prediction_l"]:
    de_en[element] = zscore(de_en[element])
    
de_en__train = de_en.iloc[:int(de_en.shape[0]*0.7),:]
de_en__test = de_en.iloc[int(de_en.shape[0]*0.7):,:]

X = de_en__train.iloc[:,1:]
Y = de_en__train.iloc[:,0]
X_test = de_en__test.iloc[:,1:]
Y_test = de_en__test.iloc[:,0] 
X_full = de_en.iloc[:,1:]
Y_full = de_en.iloc[:,0] 

model_de_en = LinearRegression()
model_de_en.fit(X,Y)

final_model_de_en = LinearRegression()
final_model_de_en.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_de_en.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.338923      0.327532
prediction_e -0.338923      1.000000     -0.821464
prediction_l  0.327532     -0.821464      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.229509      0.229898
prediction_e -0.229509      1.000000     -0.627039
prediction_l  0.229898     -0.627039      1.000000

                    z-score  regression_values
z-score            1.000000           0.334589
regression_values  0.334589           1.000000

                    z-score  regression_values
z-score            1.000000           0.229036
regression_values  0.229036           1.000000

## CS - EN

In [11]:
l = pd.read_csv(lexical_path + 'cs_en_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_cs_en.csv')

l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
cs_en = e
cs_en["prediction_l"] = l["prediction_l"]

p = cs_en.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = cs_en.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

for element in ["prediction_e", "prediction_l"]:
    cs_en[element] = zscore(cs_en[element])
    
cs_en__train = cs_en.iloc[:int(cs_en.shape[0]*0.7),:]
cs_en__test = cs_en.iloc[int(cs_en.shape[0]*0.7):,:]

X = cs_en__train.iloc[:,1:]
Y = cs_en__train.iloc[:,0]
X_test = cs_en__test.iloc[:,1:]
Y_test = cs_en__test.iloc[:,0] 
X_full = cs_en.iloc[:,1:]
Y_full = cs_en.iloc[:,0] 

model_cs_en = LinearRegression()
model_cs_en.fit(X,Y)

final_model_cs_en = LinearRegression()
final_model_cs_en.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_cs_en.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.458343      0.482772
prediction_e -0.458343      1.000000     -0.857330
prediction_l  0.482772     -0.857330      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.304323       0.32567
prediction_e -0.304323      1.000000      -0.66880
prediction_l  0.325670     -0.668800       1.00000

                    z-score  regression_values
z-score            1.000000           0.486976
regression_values  0.486976           1.000000

                    z-score  regression_values
z-score            1.000000           0.327814
regression_values  0.327814           1.000000

## ZH - EN

In [12]:
l = pd.read_csv(lexical_path + 'zh_en_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_zh_en.csv')

l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
zh_en = e
zh_en["prediction_l"] = l["prediction_l"]

p = zh_en.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = zh_en.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

for element in ["prediction_e", "prediction_l"]:
    zh_en[element] = zscore(zh_en[element])
    
zh_en__train = zh_en.iloc[:int(zh_en.shape[0]*0.7),:]
zh_en__test = zh_en.iloc[int(zh_en.shape[0]*0.7):,:]

X = zh_en__train.iloc[:,1:]
Y = zh_en__train.iloc[:,0]
X_test = zh_en__test.iloc[:,1:]
Y_test = zh_en__test.iloc[:,0] 
X_full = zh_en.iloc[:,1:]
Y_full = zh_en.iloc[:,0] 

model_zh_en = LinearRegression()
model_zh_en.fit(X,Y)

final_model_zh_en = LinearRegression()
final_model_zh_en.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_zh_en.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.346380      0.365341
prediction_e -0.346380      1.000000     -0.843998
prediction_l  0.365341     -0.843998      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.227146      0.243662
prediction_e -0.227146      1.000000     -0.668513
prediction_l  0.243662     -0.668513      1.000000

                    z-score  regression_values
z-score            1.000000           0.364932
regression_values  0.364932           1.000000

                    z-score  regression_values
z-score            1.000000           0.244662
regression_values  0.244662           1.000000

## EN - ZH

In [13]:
l = pd.read_csv(lexical_path + 'en_zh_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_en_zh.csv')

l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
en_zh = e
en_zh["prediction_l"] = l["prediction_l"]

p = en_zh.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = en_zh.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

for element in ["prediction_e", "prediction_l"]:
    en_zh[element] = zscore(en_zh[element])
    
en_zh__train = en_zh.iloc[:int(en_zh.shape[0]*0.7),:]
en_zh__test = en_zh.iloc[int(en_zh.shape[0]*0.7):,:]

X = en_zh__train.iloc[:,1:]
Y = en_zh__train.iloc[:,0]
X_test = en_zh__test.iloc[:,1:]
Y_test = en_zh__test.iloc[:,0] 
X_full = en_zh.iloc[:,1:]
Y_full = en_zh.iloc[:,0] 

model_en_zh = LinearRegression()
model_en_zh.fit(X,Y)

final_model_en_zh = LinearRegression()
final_model_en_zh.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_en_zh.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.438748      0.424316
prediction_e -0.438748      1.000000     -0.726890
prediction_l  0.424316     -0.726890      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.289216      0.299679
prediction_e -0.289216      1.000000     -0.547429
prediction_l  0.299679     -0.547429      1.000000

                    z-score  regression_values
z-score            1.000000           0.461395
regression_values  0.461395           1.000000

                    z-score  regression_values
z-score            1.000000           0.305659
regression_values  0.305659           1.000000

## EN - FI

In [14]:
l = pd.read_csv(lexical_path + 'en_fi_predictions.csv')
e = pd.read_csv(embeddings_path + 'train_all_with_predictions_en_fi.csv')

l = l[["prediction"]].rename(columns={"prediction":"prediction_l"})
e = e[["z-score", "prediction"]].rename(columns={"prediction":"prediction_e"})
en_fi = e
en_fi["prediction_l"] = l["prediction_l"]

p = en_fi.corr()
display(p)
p_e.append(p.iloc[1,0])
p_l.append(p.iloc[2,0])

k = en_fi.corr(method="kendall")
display(k)
k_e.append(k.iloc[1,0])
k_l.append(k.iloc[2,0])

for element in ["prediction_e", "prediction_l"]:
    en_fi[element] = zscore(en_fi[element])
    
en_fi__train = en_fi.iloc[:int(en_fi.shape[0]*0.7),:]
en_fi__test = en_fi.iloc[int(en_fi.shape[0]*0.7):,:]

X = en_fi__train.iloc[:,1:]
Y = en_fi__train.iloc[:,0]
X_test = en_fi__test.iloc[:,1:]
Y_test = en_fi__test.iloc[:,0] 
X_full = en_fi.iloc[:,1:]
Y_full = en_fi.iloc[:,0] 

model_en_fi = LinearRegression()
model_en_fi.fit(X,Y)

final_model_en_fi = LinearRegression()
final_model_en_fi.fit(X_full, Y_full)
    
result = pd.DataFrame(Y_test)
result["regression_values"] = model_en_fi.predict(X_test)

p = result.corr()
display(p)
pearsons.append(p.iloc[1,0])

k = result.corr(method="kendall")
display(k)
kendalls.append(k.iloc[1,0])

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.611525      0.549302
prediction_e -0.611525      1.000000     -0.870826
prediction_l  0.549302     -0.870826      1.000000

               z-score  prediction_e  prediction_l
z-score       1.000000     -0.397209      0.363198
prediction_e -0.397209      1.000000     -0.686088
prediction_l  0.363198     -0.686088      1.000000

                    z-score  regression_values
z-score            1.000000           0.490246
regression_values  0.490246           1.000000

                    z-score  regression_values
z-score            1.000000           0.325104
regression_values  0.325104           1.000000

# RESULTS

## Combined with Regression

In [15]:
r_total = pd.DataFrame([pearsons, kendalls], columns = ["ru_en", "de_en","cs_en","zh_en", "en_zh", "en_fi"], index=["pearson", "kendall"])
r_total["mean"] = r_total.T.mean()
r_total

            ru_en     de_en     cs_en     zh_en     en_zh     en_fi      mean
pearson  0.371456  0.334589  0.486976  0.364932  0.461395  0.490246  0.418266
kendall  0.258672  0.229036  0.327814  0.244662  0.305659  0.325104  0.281824

## Lexical only

In [16]:
r_lex = pd.DataFrame([p_l, k_l], columns = ["ru_en", "de_en","cs_en","zh_en", "en_zh", "en_fi"], index=["pearson", "kendall"])
r_lex["mean"] = r_lex.T.mean()
r_lex

            ru_en     de_en     cs_en     zh_en     en_zh     en_fi      mean
pearson  0.365853  0.327532  0.482772  0.365341  0.424316  0.549302  0.419186
kendall  0.251615  0.229898  0.325670  0.243662  0.299679  0.363198  0.285621

## Embeddings only

In [17]:
r_emb = pd.DataFrame([p_e, k_e], columns = ["ru_en", "de_en","cs_en","zh_en", "en_zh", "en_fi"], index=["pearson", "kendall"])
r_emb["mean"] = r_emb.T.mean()
r_emb

            ru_en     de_en     cs_en     zh_en     en_zh     en_fi      mean
pearson -0.356313 -0.338923 -0.458343 -0.346380 -0.438748 -0.611525 -0.425039
kendall -0.241806 -0.229509 -0.304323 -0.227146 -0.289216 -0.397209 -0.281535